apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  labels:
    app.kubernetes.io/instance: eks-osaka-app
  name: eks-osaka
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 192.168.0.0/16
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta2
    kind: AWSManagedControlPlane
    name: eks-osaka-control-plane
  infrastructureRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta2
    kind: AWSManagedControlPlane
    name: eks-osaka-control-plane
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta2
kind: AWSManagedControlPlane
metadata:
  name: eks-osaka-control-plane
  namespace: default
spec:
  region: ap-northeast-3
  sshKeyName: eks-osaka
  version: v1.30.0
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: eks-osaka-pool-0
  namespace: default
spec:
  clusterName: eks-osaka
  replicas: 2
  template:
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: eks-osaka
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
        kind: AWSManagedMachinePool
        name: eks-osaka-pool-0
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSManagedMachinePool
metadata:
  name: eks-osaka-pool-0
  namespace: default
spec: {}
