apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: eks-tokyo
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 192.168.0.0/16
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: AWSManagedControlPlane
    name: eks-tokyo-control-plane
  infrastructureRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: AWSManagedControlPlane
    name: eks-tokyo-control-plane
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: AWSManagedControlPlane
metadata:
  name: eks-tokyo-control-plane
  namespace: default
spec:
  region: ap-northeast-1
  sshKeyName: eks-tokyo
  version: v1.30.0
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: eks-tokyo-pool-0
  namespace: default
spec:
  clusterName: eks-tokyo
  replicas: 2
  template:
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: eks-tokyo
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AWSManagedMachinePool
        name: eks-tokyo-pool-0
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSManagedMachinePool
metadata:
  name: eks-tokyo-pool-0
  namespace: default
spec: {}
